//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

struct SlideConfiguration {

    /// Edit the slide size.
    let size = SlideSize.standard16_9

    ///  Add your slides into the trailing closure.
    let slideIndexController = SlideIndexController {
        TitleSlide()
        XcodePreviewSlide()
        AgendaSlide()
        AgendaSlide(highlight: 1)
        SampleAppSlide()
        SearchScreenCaptureSlide()
        SampleAppStructureSlide()
        SimpleSampleViewCodeSlide()
        SimpleSamplePreviewCodeSlide()
        SimpleImplementationIssueSlide()
        CenterTitleSlide("Dependency Injection")
        CenterTitleSlide("Initializer Injection")
        SimpleDISampleViewModelCodeSlide()
        SimpleDISampleViewCodeSlide()
        SimpleDIMockSlide()
        InitInjectionSlide()
        PassingHardAppStructureSlide()
        BaketsuRelayIssueSlide()
        BaketsuRelayIssue2Slide()
        CenterTitleSlide("@Environment\n@EnvironmentObject")
        EnvironmentSlide()
        EnvironmentIssue1Slide()
        EnvironmentIssue2Slide()
        IssueComparingSlide()

        AgendaSlide(highlight: 2)
        XcodePreviewConcernSlide()
        IdeaSlide()
        DependencyProviderSlide()
        DependencyProviderImplementation1Slide()
        DependencyProviderImplementation2Slide()
        DependencyProviderImplementation3Slide()
        HowToUseDependencyProvider1Slide()
        HowToUseDependencyProvider2Slide()
        PreviewImageSlide()
        Benefit0Slide()
        Benefit1Slide()
        Benefit2Slide()
        Benefit3Slide()
        UIKitSlide()

        WrapUpSlide()
    }
}
